[features]
seeds = false
[programs.devnet]
dragon_staking_contract = "AK5penqfSfF1BeKj2xE6xnjNNra8EbQ2bWqaTx566Waa" 

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/alphabets/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
